(function(){
'use strict';
const $=id=>document.getElementById(id),R=StrollerRoutes;
const selected={from:null,to:null};let timetable=null,busy=false,locationVersion=0;
const clock=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Stockholm',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
const datefmt=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'});
function today(){const p=datefmt.formatToParts(new Date());return ['year','month','day'].map(t=>p.find(x=>x.type===t).value).join('-')}
function now(){const p=clock.formatToParts(new Date());const v=t=>Number(p.find(x=>x.type===t).value);return v('hour')*3600+v('minute')*60+v('second')}
function hhmm(s){s=((s%86400)+86400)%86400;return String(Math.floor(s/3600)).padStart(2,'0')+':'+String(Math.floor(s%3600/60)).padStart(2,'0')}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
async function get(url){const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Could not load timetable or location data. Try again later.');return r.json()}
for(const key of ['from','to'])$(key).addEventListener('input',()=>{if(key==='from')locationVersion++;selected[key]=null;$(key+'-choices').replaceChildren();$(key+'-selected').textContent='';$('results').replaceChildren()});
$('use-location').onclick=()=>{
 if(busy)return;
 if(!navigator.geolocation){$('status').textContent='Location is unavailable in this browser. Enter your starting place instead.';return}
 const version=++locationVersion;const button=$('use-location');button.disabled=true;$('search').disabled=true;
 $('status').textContent='Waiting for location permission...';
 const finish=()=>{button.disabled=false;if(!busy)$('search').disabled=false};
 navigator.geolocation.getCurrentPosition(position=>{
  finish();if(version!==locationVersion)return;
  const {latitude,longitude,accuracy}=position.coords;
  if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||!Number.isFinite(accuracy)||accuracy>650){$('status').textContent='Location is too approximate. Enter a starting place or try again outdoors.';return}
  selected.from={id:'device-location',name:'Current location',type:'location',coord:[latitude,longitude]};
  $('from').value='Current location';$('from-choices').replaceChildren();$('results').replaceChildren();
  $('from-selected').textContent='Phone location · accuracy about '+Math.ceil(accuracy)+' m';
  $('status').textContent='Starting point set. Choose a destination, then find bus routes.';
 },error=>{finish();if(version!==locationVersion)return;$('status').textContent=error.code===1?'Location permission was denied. Enter your starting place instead.':error.code===3?'Location timed out. Try again or enter your starting place.':'Could not find your location. Try again or enter your starting place.'},
 {enableHighAccuracy:true,timeout:15000,maximumAge:0});
};
async function choose(key){if(selected[key])return true;const data=await get(R.lookupURL($(key).value.trim()));const matches=(data.locations||[]).filter(l=>l.id&&l.name&&l.coord?.length===2);if(!matches.length)throw Error('No place found. Try a nearby bus stop or fuller address.');$(key+'-choices').replaceChildren();for(const l of matches.slice(0,8)){const b=el('button',l.name+' ('+l.type+')');b.type='button';b.onclick=()=>{if(key==='from')locationVersion++;selected[key]=l;$(key).value=l.name;$(key+'-choices').replaceChildren();$(key+'-selected').textContent='Selected '+l.type;$('status').textContent='Press Find bus routes to continue.'};$(key+'-choices').append(b)}$('status').textContent='Choose your '+key+' above.';return false}
function distance(a,b){const rad=Math.PI/180;const x=(a.lat-b.lat)*rad,y=(a.lon-b.lon)*rad;const z=Math.sin(x/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(y/2)**2;return 6371000*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function nearby(place){const point={lat:place.coord[0],lon:place.coord[1]};return timetable.stops.map((s,i)=>({stop:i,metres:distance(point,s)})).filter(s=>s.metres<=650).sort((a,b)=>a.metres-b.metres).map(s=>({stop:s.stop,seconds:Math.ceil(s.metres*1.35/0.9)+60}))}
async function load(){const date=today();if(timetable?.date===date)return;const manifest=await get('data/manifest.json');const item=manifest.dates.find(d=>d.date===date);if(!item)throw Error('No valid timetable for today. Waiting for the next data refresh.');if(Date.now()-Date.parse(manifest.builtAt)>48*3600000)throw Error('Timetable refresh is overdue. Routing is paused until fresh data is available.');if(item.bytes>20_000_000)throw Error('Timetable is too large for this phone version.');$('status').textContent='Loading today’s bus timetable…';const r=await fetch('data/'+item.file);if(!r.ok)throw Error('Could not load today’s timetable.');const stream=r.body.pipeThrough(new DecompressionStream('gzip'));timetable=await new Response(stream).json();$('data-date').textContent='Timetable for '+date+' · updated '+manifest.builtAt.slice(0,10)+' · scheduled times, not live';}
function run(query){return new Promise((resolve,reject)=>{const worker=new Worker('engine/worker.js');const timer=setTimeout(()=>{worker.terminate();reject(Error('Route search took too long. Try closer bus stops.'))},20000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();e.data.error?reject(Error(e.data.error)):resolve(e.data.result)};worker.onerror=()=>{clearTimeout(timer);worker.terminate();reject(Error('Route search failed. Please try again.'))};worker.postMessage({data:timetable,query})})}
function render(r){const card=el('article');card.append(el('div',hhmm(now())+' - '+hhmm(r.arrival),'summary'));card.append(el('div','Scheduled · '+Math.ceil((r.arrival-now())/60)+' min · '+r.path.filter(p=>p.kind==='bus').length+' buses','small'));const overview=el('div',undefined,'route-overview');card.append(el('h2','Route map'));card.append(overview);RouteMap.draw(overview,r,timetable,selected.from,selected.to);card.append(el('p','Blue: bus stop sequence. Dashed: estimated walk. Lines join stops, not exact streets.','small'));
 const legend=el('ol',undefined,'map-legend');r.path.filter(p=>p.kind==='bus').forEach(p=>legend.append(el('li','Bus '+p.line+' · '+timetable.stops[p.from].name+' → '+timetable.stops[p.to].name)));card.append(legend);const consent=el('button','Show street map');consent.type='button';const privacy=el('p','Loads OpenStreetMap tiles. OpenStreetMap receives your IP, site referrer and viewed map area. No analytics or GPS tracking.','small');card.append(consent,privacy);consent.onclick=async()=>{consent.disabled=true;try{await RouteMap.street(overview,r,timetable,selected.from,selected.to);consent.remove();privacy.textContent='Street map: OpenStreetMap. Blue bus lines join stops, not exact roads. Tap dots for stop names.'}catch(e){privacy.textContent=e.message;consent.disabled=false}};const list=el('ol',undefined,'legs');for(const p of r.path){const li=el('li');if(p.kind==='bus'){li.append(el('span','Bus '+p.line,'badge'));li.append(el('div',hhmm(p.departure)+' · '+timetable.stops[p.from].name,'stop'));li.append(el('div',hhmm(p.arrival)+' · Get off at '+timetable.stops[p.to].name,'stop'));li.append(el('div','Check the reader when boarding.','warn'))}else{li.append(el('span','Walk · about '+Math.ceil(p.seconds/60)+' min','badge'));li.append(el('div',(p.from===undefined?selected.from.name:timetable.stops[p.from].name)+' → '+(p.to===undefined?selected.to.name:timetable.stops[p.to].name),'stop'));li.append(el('div','Estimated walk. Check the street route.','small'))}list.append(li)}card.append(list);return card}
$('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;for(const id of ['from','to','search','use-location'])$(id).disabled=true;$('results').replaceChildren();try{if(!await choose('from')||!await choose('to'))return;await load();const access=nearby(selected.from),egress=nearby(selected.to);if(!access.length||!egress.length)throw Error('No allowed bus stop within 650 m of a selected place. Choose a nearby bus stop.');$('status').textContent='Searching the bus network without lines 1-6…';const result=await run({departure:now(),access,egress,maxBoardings:5});if(!result){$('status').textContent='No route found within 650 m walks and 4 transfers and 4 hours in today’s timetable. Try nearby bus stops.';return}$('status').textContent='Earliest arrival found in the allowed bus network.';$('results').append(render(result));$('results').scrollIntoView({behavior:'smooth'})}catch(e){$('status').textContent=e.message}finally{busy=false;for(const id of ['from','to','search','use-location'])$(id).disabled=false}};
})();
